In [1]:
!wget https://archive.ics.uci.edu/static/public/222/bank+marketing.zip

--2023-11-27 10:15:27--  https://archive.ics.uci.edu/static/public/222/bank+marketing.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘bank+marketing.zip’

bank+marketing.zip      [    <=>             ] 999.85K  1.07MB/s    in 0.9s    

2023-11-27 10:15:29 (1.07 MB/s) - ‘bank+marketing.zip’ saved [1023843]



In [2]:
!unzip bank+marketing.zip

Archive:  bank+marketing.zip
 extracting: bank.zip                
 extracting: bank-additional.zip     


In [3]:
!unzip bank.zip


Archive:  bank.zip
  inflating: bank-full.csv           
  inflating: bank-names.txt          
  inflating: bank.csv                


In [4]:
import csv

def recode(row):
  match row[1]:
    case "admin.":
      job = 1
    case "unknown":
      job = 2
    case "unemployed":
      job = 3
    case "management":
      job = 4
    case "housemaid":
      job = 5
    case "entrepreneur":
      job = 6
    case "student":
      job = 7
    case "blue-collar":
      job = 8
    case "self-employed":
      job = 9
    case "retired":
      job = 10
    case "technician":
      job = 11
    case "services":
      job = 12

  if row[2] == 'divorced':
    marital = -1
  elif row[2] == 'married':
    marital = +1
  elif row[2] == 'single':
    marital = 0

  #print(row[3])
  # categorical: "unknown","secondary","primary","tertiary")
  match row[3]:
    case "unknown":
      education = 0
    case "secondary":
      education = 2
    case "primary":
      education = 1
    case "tertiary":
      education = 3

  #default – "yes" - 1,"no" - 0
  if row[4] == "yes":
    default = 1
  else:
    default = 0

  #housing – "yes" - 1,"no" - 0
  if row[6] == "yes":
    housing = 1
  else:
    housing = 0

  #loan – "yes" - 1,"no" - 0
  if row[7] == "yes":
    loan = 1
  else:
    loan = 0

  if row[8] == "unknown":
    contact = 0
  elif row[8] == "telephone":# - 1, "cellular" - 2
    contact = 1
  elif row[8] == "cellular":
    contact = 2

  #row[10] #month – "jan" - 1, "feb" - 2, "mar" - 3, “apr” - 4, “may” - 5, “jun” - 6, “jul” - 7, “aug” - 8, “sep” - 9, “oct” - 10, "nov" - 11, "dec" - 12
  match row[10]:
    case "jan":
      month = 1
    case "feb":
      month = 2
    case "mar":
      month = 3
    case "apr":
      month = 4
    case "may":
      month = 5
    case "jun":
      month = 6
    case "jul":
      month = 7
    case "aug":
      month = 8
    case "sep":
      month = 9
    case "oct":
      month = 10
    case "nov":
      month = 11
    case "dec":
      month = 12

  match row[15]:
    case "unknown":
      poutcome = 0
    case "other":
      poutcome = 1
    case "failure":
      poutcome = -1
    case "success":
      poutcome = 2

  if row[16] == "yes":
    y = 1
  else:
    y = 0

  #return [row[0], job, marital, education ]
  return  [int(row[0]), job, marital, education, default, int(row[5]), housing, loan, contact, int(row[9]), month,
         int(row[11]), int(row[12]), int(row[13]), int(row[14]), poutcome, y]

numrows = 0
recoded = [] # числовий масив даних

with open('bank-full.csv', newline='') as csvfile:
    data = csv.reader(csvfile, delimiter=";", quotechar='"')
    next(data)
    for row in data:
      #print(numrows)
      res = recode(row)
      recoded.append(res)
      numrows += 1
      #print(res)

print(numrows)
print(recoded[0])
print(recoded[1])


#f.close

45211
[58, 4, 1, 3, 0, 2143, 1, 0, 0, 5, 5, 261, 1, -1, 0, 0, 0]
[44, 11, 0, 2, 0, 29, 1, 0, 0, 5, 5, 151, 1, -1, 0, 0, 0]


In [5]:
f = open('bank.txt', 'w')
for row in recoded:
  for col in row:
    f.write(str(col) + "\t")
  f.write("\n")
f.close()

In [6]:
print(recoded[45176])

[54, 1, 1, 2, 0, 66, 1, 0, 2, 11, 11, 167, 1, -1, 0, 0, 1]


In [7]:
print(recoded[45177])

[36, 1, -1, 2, 0, 1224, 1, 0, 2, 12, 11, 482, 1, 374, 1, 2, 1]


In [8]:
import numpy as np
from sklearn.linear_model import LogisticRegression

In [9]:
data = np.array(recoded)

In [10]:
Y = data[:,-1]
X = data[:,:-1]

In [11]:
X.shape

(45211, 16)

In [12]:
Y.shape

(45211,)

In [13]:
logistic = LogisticRegression(max_iter=100000)

In [14]:
logistic.fit(X, Y)

LogisticRegression(max_iter=100000)

In [15]:
logistic.coef_

array([[ 5.68743899e-05, -1.95463451e-02, -1.73076875e-01,
         1.02018169e-01, -2.49048351e-01,  1.94973339e-05,
        -9.05402047e-01, -1.08521872e+00,  5.26218780e-01,
        -7.06656001e-03, -1.50170575e-02,  3.93668197e-03,
        -1.16242039e-01,  2.05697800e-03,  3.31683153e-02,
         7.97910326e-01]])

In [16]:
logistic.intercept_

array([-3.36648107])

In [17]:
from sklearn.model_selection import train_test_split

X_train_full, X_test, y_train_full, y_test = train_test_split(X, Y, random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(X_train_full, y_train_full, random_state=42)

In [18]:
X_train_full.shape

(33908, 16)

In [19]:
X_test.shape

(11303, 16)

In [20]:
X_train.shape

(25431, 16)

In [21]:
X_valid.shape

(8477, 16)

In [62]:
from sklearn.neural_network import MLPRegressor

mlp_reg = MLPRegressor(hidden_layer_sizes=[24, 8], activation='logistic', random_state=42)

In [63]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler # (x-ave)/stdev

pipeline = make_pipeline(StandardScaler(), mlp_reg)

In [64]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('mlpregressor',
                 MLPRegressor(activation='logistic', hidden_layer_sizes=[24, 8],
                              random_state=42))])

In [65]:
y_pred = pipeline.predict(X_valid)

In [66]:
y_pred

array([ 0.15542785,  0.46826869,  0.37071697, ...,  0.42886901,
       -0.00864353,  0.01010677])

In [67]:
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_valid, y_pred, squared=False) # about 0.505

In [68]:
rmse

0.26645689463584166

In [69]:
y_hat_prob = pipeline.predict(X)

In [70]:
y_hat_prob

array([ 0.019308  , -0.00255851,  0.00109241, ...,  0.89611941,
        0.25170074,  0.59680763])

In [71]:
y_hat = []

for element in y_hat_prob:
  if element>=0.5:
    y_hat.append(1)
  else:
    y_hat.append(0)

#y_hat

In [72]:
total = len(y_hat)
error = 0
fpos = 0
fneg = 0

for i in range(total):
  if Y[i] != y_hat[i]:
    error+=1
  if Y[i] == 0 and y_hat[i] == 1:
    fpos+=1
  if Y[i] == 1 and y_hat[i] == 0:
    fneg+=1

print("Відсоток помилок = ", 100.*error/total, ", false positive = ", 100.*fpos/total, ", false negative = ", 100.*fneg/total)


Відсоток помилок =  9.940058835239212 , false positive =  2.229545906969543 , false negative =  7.710512928269669


In [73]:
mlp_reg.coefs_

[array([[ 2.58976502e-02,  1.07201247e-01,  1.11860712e-01,
         -1.77605470e-01, -2.41271261e-02, -2.38226359e-01,
         -1.78955322e-02,  3.72813669e-02,  1.06221947e-01,
         -8.37157051e-02, -4.04534946e-01,  2.29844589e-01,
         -6.50785519e-02,  5.43725062e-02, -1.57433735e-01,
         -4.12842836e-02, -1.04560093e+00,  4.91346413e-02,
          9.38979490e-02, -1.72100366e-01,  9.95011744e-02,
         -5.78566225e-02,  4.15472587e-02,  3.41096965e-03],
        [-4.29997209e-02,  1.75512156e-01, -8.81359347e-02,
          3.56084157e-02,  1.25309840e-01, -2.28627196e-01,
          1.45774321e-02,  2.78071859e-02, -1.37943062e-01,
          1.28275838e-01,  1.66671773e-01, -1.48463329e-01,
         -6.46858477e-02, -7.69510788e-02,  3.68643730e-02,
          3.75836065e-02, -2.70052871e-01, -2.58849160e-02,
         -1.41623118e-01,  7.42236911e-02, -8.24492201e-02,
         -1.30016806e-02, -1.18149452e-02, -3.52064223e-02],
        [ 1.67933865e-01, -7.76539304e

In [74]:
mlp_reg.intercepts_

[array([-0.50714605,  0.21592962, -0.51551125, -0.11801161, -0.02245648,
         0.27132414,  0.16472811, -1.41710228, -0.59262066,  0.52549297,
         0.20524881,  0.12347108,  0.40517731,  0.03987057,  0.39052701,
         0.11953287, -0.66858716,  0.27404945, -0.42658645,  0.83246683,
        -0.46765203,  1.27156337, -0.80250427, -0.5983767 ]),
 array([-0.31740507, -0.06940779, -0.2167388 , -0.23542976, -0.13476782,
         0.02493852, -0.16673281, -0.16492451]),
 array([-0.3300633])]

In [75]:
number = len(mlp_reg.coefs_)

for i in range(number):
  print("\nМатриця ", i, " -> ", i+1, "\n")
  for j in range(len(mlp_reg.coefs_[i])):
    for k in range(len(mlp_reg.coefs_[i][j])):
      print(mlp_reg.coefs_[i][j][k], end="\t")
    print()
  for j in range(len(mlp_reg.intercepts_[i])):
    print(mlp_reg.intercepts_[i][j], end="\t")
  print()



Матриця  0  ->  1 

0.02589765018690573	0.10720124668354175	0.11186071249402382	-0.17760546999271462	-0.024127126122970757	-0.23822635899778646	-0.017895532186119778	0.03728136693965316	0.1062219467375268	-0.08371570508335287	-0.4045349458662035	0.22984458913343833	-0.06507855191640805	0.05437250624304404	-0.15743373533187177	-0.04128428362388602	-1.045600932226808	0.04913464134218399	0.09389794902241907	-0.1721003659952508	0.09950117441317731	-0.05785662248514405	0.04154725868731849	0.0034109696483493822	
-0.04299972088822037	0.17551215572464915	-0.08813593472962668	0.03560841566151733	0.12530983983624017	-0.2286271957853732	0.014577432116025555	0.02780718585284638	-0.13794306193007433	0.12827583839351026	0.16667177342032874	-0.14846332934167916	-0.06468584772688558	-0.07695107875680433	0.036864372958342065	0.03758360647079096	-0.27005287067255773	-0.025884915977167716	-0.1416231176642451	0.07422369108983455	-0.08244922007471352	-0.01300168055979432	-0.011814945178123742	-0.035206422

In [79]:

#age (число) – вік
#job (текст) – ким працює: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student", "blue-collar","self-employed","retired" (на пенсії),"technician","services"
#marital	(текст) – брачний статус: 'divorced' (розлучений(а), удівець (удова)), 'married', 'single'
#education	(текст) – рівень освіти: "unknown","secondary","primary","tertiary" (закінчив університет)
#default (текст) – наявність кредитної заборгованості: "yes","no" (відсутня)
#balance (число) – середній річний баланс рахунку (у євро)
#housing (текст) – наявність кредиту: "yes","no"
#loan (текст) – наявність кредиту: "yes","no"
#contact (текст) – як зв’язувались: "unknown", "telephone" (стаціонарним телефоном), "cellular"
#day (число) – день місяця
#month (текст) - місяць: "jan", "feb", "mar", ..., "nov", "dec" (грудень)
#duration (число) - тривалість дзвінка у секундах
#campaign (число) - кількість дзвінків
#pdays (число) - кількість днів з попереднього дзвінка (-1 для першого контакту)
#previous (число) - кількість дзвінків від банку до початку поточної кампанії
#poutcome (текст) - результат попередньої кампанії: "unknown", "other", "failure", "success" (вдалий)



Ймовірність того, що даний клієнт покладе кошти на депозит - 0.11105826237921024
Не варто телефонувати


In [89]:
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

@interact
def g(age=(18, 122),
      job = [("admin.", 1), ("unknown", 2), ("unemployed", 3), ("management", 4), ("housemaid", 5), ("entrepreneur", 6), ("student", 7),
       ("blue-collar", 8), ("self-employed", 9), ("retired", 10), ("technician", 11), ("services", 12)],
      marital=[('divorced',-1), ('married', +1), ('single', 0)],
      education = [("unknown", 0), ("secondary", 2), ("primary", 1), ("tertiary", 3)],
      default = [("yes", 1), ("no", 0)],
      balance=(-10000, 200000),
      housing = [("yes", 1), ("no", 0)],
      loan = [("yes", 1), ("no", 0)],
      contact = [("unknown", 0), ("telephone", 1), ("cellular", 2)],
      day=(1,31),
      month = [("jan", 1), ("feb", 2), ("mar", 3), ("apr", 4), ("may", 5), ("jun", 6), ("jul", 7), ("aug", 8), ("sep", 9), ("oct", 10), ("nov", 11), ("dec", 12)],
      duration = (0, 5000),
      campaign=(1, 100),
      pdays=(-1, 1000),
      previous=(0, 300),
      poutcome = [("unknown",  0), ("other", 1), ("failure", -1), ("success",2)]):
    client = [[age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous, poutcome]]
    y_hat_client = pipeline.predict(client)

    print("Ймовірність того, що даний клієнт покладе кошти на депозит -", y_hat_client[0])
    threshold = 0.25
    if y_hat_client[0]> threshold:
      print("Спробуйте зателефонувати")
    else:
      print("Не варто телефонувати")




interactive(children=(IntSlider(value=70, description='age', max=122, min=18), Dropdown(description='job', opt…

23

interactive(children=(Checkbox(value=True, description='x'), FloatSlider(value=1.0, description='y', max=3.0, …